apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
    app: student-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-deployment-pods
  template:
    metadata:
      name: student-deployment
      labels:
        app: student-deployment-pods
    spec:
      containers:
        - name: student-deployment
          image: ogleh/students:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: service
              value: course-service


---

apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-deployment-pods
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
#      nodePort: 30000
